
## Docker Compose setup
#  PostgreSQL database (book_social_network) with persistent storage.
#  MailDev service for testing emails.
#  custom network (spring-demo) to connect these services.


  services:
    postgres:
      container_name: postgres-sql-sbn
      image: postgres
      environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
        PGDATA: /var/lib/postgres/data
        POSTGRES_DB: book_social_network
      volumes:
        - postgres:/data/postgres
      ports:
        - 5432:5432
      networks:
        - spring-demo
      restart: unless-stopped
    mail-dev:
      container_name: maid-dev-bsn
      image: maildev/maildev
      ports:
        - 1080:1080
        - 1025:1025

  networks:
    spring-demo:
      driver: bridge

  volumes:
    postgres:
      driver: local
